"""add_user_name_column

Revision ID: 0b5e0e1353d2
Revises: f509baaeb1b9
Create Date: 2026-03-29 22:24:57.142331
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b5e0e1353d2"
down_revision: Union[str, None] = "f509baaeb1b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    # ### end Alembic commands ###
