"""unified_memory_architecture

Revision ID: f509baaeb1b9
Revises: 
Create Date: 2026-03-29 12:14:49.464752
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f509baaeb1b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evergreen_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', postgresql.ENUM('fact', 'preference', 'relationship', 'goal', name='evergreen_category'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', postgresql.ENUM('manual', 'profile_extract', name='evergreen_source'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evergreen_memories_user_id'), 'evergreen_memories', ['user_id'], unique=False)
    op.create_index('ix_evergreen_user_category', 'evergreen_memories', ['user_id', 'category'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('entry_type', postgresql.ENUM('episode', 'event', 'foresight', name='entry_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2560), nullable=True),
    sa.Column('memcell_id', sa.UUID(), nullable=True),
    sa.Column('participants', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memcell_id'], ['memcells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_group_id'), 'knowledge_entries', ['group_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_user_id'), 'knowledge_entries', ['user_id'], unique=False)
    op.create_index('ix_knowledge_memcell', 'knowledge_entries', ['memcell_id'], unique=False)
    op.create_index('ix_knowledge_user_created', 'knowledge_entries', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_knowledge_user_type', 'knowledge_entries', ['user_id', 'entry_type'], unique=False)
    op.drop_index(op.f('ix_memory_chunks_user_created'), table_name='memory_chunks')
    op.drop_index(op.f('ix_memory_chunks_user_id'), table_name='memory_chunks')
    op.drop_table('memory_chunks')
    op.drop_index(op.f('ix_memory_notes_user_created'), table_name='memory_notes')
    op.drop_index(op.f('ix_memory_notes_user_type'), table_name='memory_notes')
    op.drop_table('memory_notes')
    op.drop_index(op.f('ix_event_log_records_group_id'), table_name='event_log_records')
    op.drop_index(op.f('ix_event_log_records_user_id'), table_name='event_log_records')
    op.drop_index(op.f('ix_eventlog_group_ts'), table_name='event_log_records')
    op.drop_index(op.f('ix_eventlog_parent'), table_name='event_log_records')
    op.drop_index(op.f('ix_eventlog_user_ts'), table_name='event_log_records')
    op.drop_table('event_log_records')
    op.drop_index(op.f('ix_episodic_group_ts'), table_name='episodic_memories')
    op.drop_index(op.f('ix_episodic_group_user_ts'), table_name='episodic_memories')
    op.drop_index(op.f('ix_episodic_memories_group_id'), table_name='episodic_memories')
    op.drop_index(op.f('ix_episodic_memories_user_id'), table_name='episodic_memories')
    op.drop_index(op.f('ix_episodic_parent'), table_name='episodic_memories')
    op.drop_index(op.f('ix_episodic_user_ts'), table_name='episodic_memories')
    op.drop_table('episodic_memories')
    op.drop_index(op.f('ix_foresight_group_ts'), table_name='foresight_records')
    op.drop_index(op.f('ix_foresight_parent'), table_name='foresight_records')
    op.drop_index(op.f('ix_foresight_records_group_id'), table_name='foresight_records')
    op.drop_index(op.f('ix_foresight_records_user_id'), table_name='foresight_records')
    op.drop_index(op.f('ix_foresight_user_ts'), table_name='foresight_records')
    op.drop_table('foresight_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foresight_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('participants', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2560), autoincrement=False, nullable=True),
    sa.Column('vector_model', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('extend', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('foresight_records_pkey'))
    )
    op.create_index(op.f('ix_foresight_user_ts'), 'foresight_records', ['user_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_foresight_records_user_id'), 'foresight_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_foresight_records_group_id'), 'foresight_records', ['group_id'], unique=False)
    op.create_index(op.f('ix_foresight_parent'), 'foresight_records', ['parent_id'], unique=False)
    op.create_index(op.f('ix_foresight_group_ts'), 'foresight_records', ['group_id', 'start_time', 'end_time'], unique=False)
    op.create_table('episodic_memories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('participants', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('episode', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('linked_entities', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('memcell_event_id_list', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('parent_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2560), autoincrement=False, nullable=True),
    sa.Column('vector_model', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('extend', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('episodic_memories_pkey'))
    )
    op.create_index(op.f('ix_episodic_user_ts'), 'episodic_memories', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_episodic_parent'), 'episodic_memories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_episodic_memories_user_id'), 'episodic_memories', ['user_id'], unique=False)
    op.create_index(op.f('ix_episodic_memories_group_id'), 'episodic_memories', ['group_id'], unique=False)
    op.create_index(op.f('ix_episodic_group_user_ts'), 'episodic_memories', ['group_id', 'user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_episodic_group_ts'), 'episodic_memories', ['group_id', 'timestamp'], unique=False)
    op.create_table('event_log_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('atomic_fact', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('participants', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2560), autoincrement=False, nullable=True),
    sa.Column('vector_model', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('extend', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('event_log_records_pkey'))
    )
    op.create_index(op.f('ix_eventlog_user_ts'), 'event_log_records', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_eventlog_parent'), 'event_log_records', ['parent_id'], unique=False)
    op.create_index(op.f('ix_eventlog_group_ts'), 'event_log_records', ['group_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_event_log_records_user_id'), 'event_log_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_event_log_records_group_id'), 'event_log_records', ['group_id'], unique=False)
    op.create_table('memory_notes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('note_type', postgresql.ENUM('daily', 'evergreen', name='note_type'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('auto_flush', 'session_end', 'manual', 'compaction', name='note_source'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('memory_notes_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('memory_notes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_notes_pkey'))
    )
    op.create_index(op.f('ix_memory_notes_user_type'), 'memory_notes', ['user_id', 'note_type'], unique=False)
    op.create_index(op.f('ix_memory_notes_user_created'), 'memory_notes', ['user_id', 'created_at'], unique=False)
    op.create_table('memory_chunks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('note_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2560), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['memory_notes.id'], name=op.f('memory_chunks_note_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('memory_chunks_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_chunks_pkey'))
    )
    op.create_index(op.f('ix_memory_chunks_user_id'), 'memory_chunks', ['user_id'], unique=False)
    op.create_index(op.f('ix_memory_chunks_user_created'), 'memory_chunks', ['user_id', 'created_at'], unique=False)
    op.drop_index('ix_knowledge_user_type', table_name='knowledge_entries')
    op.drop_index('ix_knowledge_user_created', table_name='knowledge_entries')
    op.drop_index('ix_knowledge_memcell', table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_user_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_group_id'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index('ix_evergreen_user_category', table_name='evergreen_memories')
    op.drop_index(op.f('ix_evergreen_memories_user_id'), table_name='evergreen_memories')
    op.drop_table('evergreen_memories')
    # ### end Alembic commands ###
